---
documentclass: article
fontsize: 10pt
date: "`r Sys.Date()`"
output: 
  bookdown::pdf_document2: 
    fig_caption: yes
    toc: false
    latex_engine: xelatex
    includes:
      in_header: preamble.sty
      before_body: titlepage.sty
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}

update.packages("rlang")
library(xfun)
library(tidyverse)
library(rprojroot)
library(kableExtra)
library(ISLR2)
# this package does not work for the newest version of R --> 
# only load if the local data files are not there
if (!file.exists(find_root_file("data/rect_constr.csv", 
     criterion = has_file("MultivariateStatistics_assignment.Rproj")))) {
  library(smacof)
} 
 
knitr::opts_chunk$set(echo = TRUE)
```

# Task 1

All R scripts and the data can be found on [this GitHub repository](https://github.com/raiisac/MultivariateStatistics_assignment).
```{r load, include=FALSE, message=FALSE, warning=FALSE}
data(College)
```


# Task 2

```{r load2, include=FALSE, message=FALSE, warning=FALSE}
load(find_root_file("data/fashion.Rdata", 
     criterion = has_file("MultivariateStatistics_assignment.Rproj")))
train.data <- train.data %>% scale(center = TRUE, scale = FALSE)
```

# Task 3
```{r load3, include=FALSE, message=FALSE, warning=FALSE}
if (file.exists(find_root_file("data/rect_constr.csv", 
     criterion = has_file("MultivariateStatistics_assignment.Rproj")))) {
  rect_constr <- read.csv(
    find_root_file("data/rect_constr.csv", 
                   criterion = 
                     has_file("MultivariateStatistics_assignment.Rproj")))
} else {
  data(rect_constr) 
}
if (file.exists(find_root_file("data/rectangles.csv", 
     criterion = has_file("MultivariateStatistics_assignment.Rproj")))) {
  rectangles <- read.csv(
    find_root_file("data/rectangles.csv", 
                   criterion = 
                     has_file("MultivariateStatistics_assignment.Rproj")))
} else {
  data(rectangles) 
}
```

# Appendix

